## Valid token with administrator access
POST http://localhost:3002/api/ticket/estimation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJhZG1pbiIsImF1dGhJZCI6MSwiaWF0IjoxNzE5NTY3OTIyLCJleHAiOjE3MTk1Njc5ODJ9.3hRqlwhE8kve3wVVTPKx5pyxWXlca9kmWCrW5t6PuZE
Content-Type: application/json

{
  "title": "Critical Bug Fix",
  "category": "Bug"
}
###

## Valid token with basic access
POST http://localhost:3002/api/ticket/estimation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJiYXNpYyIsImF1dGhJZCI6MiwiaWF0IjoxNzE5NTY3OTIyLCJleHAiOjE3MTk1Njc5ODJ9.qhD_K3RcZ7DjiFKOA9NP7IIjeXSSDjz6dUd27y8N8Uk
Content-Type: application/json

{
  "title": "Critical Bug Fix",
  "category": "Bug"
}
###

##Expired token
POST http://localhost:3002/api/ticket/estimation HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJiYXNpYyIsImF1dGhJZCI6MiwiaWF0IjoxNzE5NTY3OTIyLCJleHAiOjE3MTk1Njc5ODJ9.qhD_K3RcZ7DjiFKOA9NP7IIjeXSSDjz6dUd27y8N8Uk
Content-Type: application/json

{
  "title": "Critical Bug Fix",
  "category": "Bug"
}
###